language: node_js
node_js:
  - "6.9.5"
services:
  - mongodb

sudo: false

addons:
  apt:
    sources:
      - mongodb-upstart
      - mongodb-3.0-precise
    packages:
      - mongodb-org-server
      - mongodb-org-shell

env:
  - NODE_ENV="test"

