language: node_js
node_js:
  - "4.2.6"

services:
  - mongodb

sudo: false

addons:
  apt:
    sources:
      - mongodb-upstart
      - mongodb-3.2-precise
    packages:
      - mongodb-org-server
      - mongodb-org-shell

env:
  - NODE_ENV="test"

